config/routes.rb
Rails.application.routes.draw do
  resources :posts, :path => "blogs" 
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  # unauthenticated :user do
  #   root 'home#index', as: :unauthenticated_root
  # end

  # authenticated :user do
  #   root 'dashboards#index', as: :authenticated_root
  # end
  get '/dashboard' => 'home#dashboard'
  get '/users/:id/blogs' => 'posts#blogs', as: 'user_blogs'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :banner, dependent: :destroy
  has_rich_text :body

  enum status: [:published, :draft, :archived]

  validates :title, presence: true
  validates :banner, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [ :author, :admin ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to dashboard_path
    end
    @posts = Post.includes(:user).all
  end

  def dashboard
    id = current_user.id
    @current_user_posts = current_user.posts
    @posts = Post.where.not(user_id: id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :blogs]
  before_action :set_post, only: %i[ show edit update destroy archive republish ]
  before_action :get_user, only: [:blogs]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  def blogs
    @posts = @user.posts
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        set_status
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        set_status
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def archive
    @post.archived!
    redirect_to post_path(@post), notice: 'Post Archived'
  end

  def republish
    @post.published!
    @post.published_at = Time.now
    @post.save
    redirect_to post_path(@post), notice: 'Post Republished'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.includes(:user).find(params[:id])
    end

    def get_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :user_id, :banner, :body)
    end

    def set_status
      if params[:commit] == "Publish"
        @post.published!
        @post.published_at = Time.now 
        @post.save 
      elsif params[:commit] == "Save as Draft"
        @post.draft!
      elsif params[:commit] == "Archive"
        @post.archived!
      end
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% end %>
  </figcaption>
</figure>

app/views/home/dashboard.html.erb
<div class="mb-10">
  <h1 class="flex items-center gap-2 text-2xl font-bold mb-4">Your Blogs</h1>

  <%= render 'shared/posts', posts: @current_user_posts %>
</div>
<div>
  <h1 class="flex items-center gap-2 text-2xl font-bold mb-4">Other Blogs</h1>

  <%= render 'shared/posts', posts: @posts %>
</div>

app/views/home/index.html.erb
<h1 class="text-2xl font-bold mb-4">Blogs</h1>
<%= render 'shared/posts', posts: @posts %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JPLDG Blog App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="flex flex-col items-center h-screen">
      <%= render 'shared/navbar' %>
      <div class="container mx-auto px-5 my-2 mt-[70px] md:mt-24">
        <% if notice %>
          <div class="p-4 py-2 text-sm text-green-700 bg-green-100 rounded-lg" role="notice">
            <%= notice %>
          </div>
        <% end %>
        <% if alert %>
          <div class="p-4 py-2 text-sm text-red-700 bg-red-100 rounded-lg" role="alert">
            <%= alert %>
          </div>
        <% end %>
      </div>
      <main class="container p-5 flex-auto"> 
        <%= yield %>
      </main>
      <footer class="w-full bg-gray-900 text-white px-5 py-2.5 md:py-5 flex items-center justify-center mt-8">
        <span class="block text-xs">© 2022 JPLDG</span>
      </footer>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<div>
  <%= form_with model: @post, data:{turbo:false}, local: true do |f| %>
    <% if @post.errors.any? %>
      <div class="w-full p-2 rounded-lg mb-2 text-red-500 bg-red-200 font-medium">
        <% @post.errors.full_messages.each do |error| %>
          <div><%= error %></div>
        <% end %>
      </div>
    <% end %>

    <div class="mb-2">
      <%= f.label :title, class: 'block font-medium' %>
      <%= f.text_field :title, class: "w-full block border rounded-lg border-gray-300 focus:ring-gray-500 focus:border-gray-500" %>
    </div>

    <div class="mb-4">
      <%= f.label :banner, class: 'block mb-1 font-medium text-gray-900' %>
      <%= f.file_field :banner, class: 'block w-full text-gray-900 rounded-lg border border-gray-300 cursor-pointer focus:outline-none file:bg-gray-200 file:rounded-lg file:hover:cursor-pointer file:hover:bg-gray-300 file:border-none file:p-2 file:rounded-r-none file:px-4' %>
    </div>

    <div class="mb-4">
      <%= f.label :body, class: 'block font-medium' %>
      <%= f.rich_text_area :body, class: 'border-gray-300 rounded-lg focus:ring-gray-500 focus:border-gray-500' %>
    </div>

    <div class="flex gap-2 items-center">
      <%= f.submit class: 'block py-1.5 px-4 font-medium text-center text-white bg-gray-900 hover:bg-gray-700 rounded-lg focus:ring-4 focus:ring-blue-200 hover:cursor-pointer' %>

      <%= link_to 'Cancel', root_path, class: 'block py-1.5 px-4 font-medium text-center text-white bg-gray-900 hover:bg-gray-700 rounded-lg focus:ring-4 focus:ring-blue-200 hover:cursor-pointer w-fit' %>
    </div>
  <% end %>
</div>

app/views/posts/blogs.html.erb
<h1 class="text-2xl font-bold mb-4">Blogs by: <span class="font-medium"><%= @user.username %></span></h1>

<%= render 'shared/posts', posts: @posts %>

app/views/posts/edit.html.erb
<h1 class="font-bold text-xl mb-4">Edit Blog</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1 class="text-2xl font-bold mb-4">All Blogs</h1>

<%= render 'shared/posts', posts: @posts %>

app/views/posts/new.html.erb
<h1 class="font-bold text-xl mb-4">New Blog</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="max-w-3xl mx-auto text-sm">
  <% if @post.banner.attached? %>
    <%= image_tag @post.banner, class: 'block mb-4 rounded-lg' %>
  <% end %>

  <div class="flex items-center justify-between mb-4">
    <span>Author: <%= link_to @post.user.username, user_blogs_path(@post.user_id), class: 'hover:underline font-medium text-blue-600' %></span>
    <% if user_signed_in? && current_user.email == @post.user.email %>
      <div class="flex items-center gap-2">
        <%= link_to edit_post_path(@post), class: 'text-blue-500 hover:text-blue-300 flex items-center' do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
          </svg>
        <% end %>
        <%= button_to post_path(@post), method: :delete, class: 'text-red-500 hover:text-red-300 flex items-center' do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
          </svg>
        <% end %>
      </div>
    <% end %>
  </div>
  <span class="block mb-4"><%= @post.updated_at.strftime("%a %b %-d %Y") %></span>
  <h1 class="font-bold text-2xl mb-2"><%= @post.title %></h1>
  <p><%= @post.body %></p>
</div>

app/views/shared/_navbar.html.erb
<nav class="w-full bg-gray-900 fixed top-0 left-0">
  <div class="container mx-auto">
    <div class="flex justify-between items-center w-full px-5 py-2.5 md:py-5">
      <%= link_to 'Simple Blog', root_path, class: 'block text-xl lg:text-2xl font-bold text-white hover:text-gray-200' %>
      <ul class="flex items center gap-5 md:gap-10">
        <% if user_signed_in? %>
          <li><%= link_to 'Write', new_post_path, class: 'block text-white font-medium hover:text-gray-200' %></li>
          <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: 'block text-white font-medium hover:text-gray-200' %>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path, class: 'block text-white font-medium hover:text-gray-200 md:px-4 md:py-2 py-1' %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path, class: 'block text-white font-medium hover:text-gray-200 px-4 md:py-2 py-1 bg-gray-600 hover:bg-gray-500 rounded-lg' %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_posts.html.erb
<div class="flex-auto grid lg:auto-rows-min grid-cols-auto md:grid-cols-2 lg:grid-cols-3 gap-5 overflow-y-auto">
  <% if posts.any? %>
    <% posts.each do |post| %>
      <div class="rounded-lg text-sm">
        <% if post.banner.attached? %>
          <%= image_tag post.banner, class: 'block w-full rounded-t-lg h-40 object-cover' %>
        <% end %>
        <div class="border border-gray-200 rounded-b-lg shadow-md p-2">
          <div class="flex items-center justify-between my-2">
            <span>Author: <%= link_to post.user.username, user_blogs_path(post.user_id), class: 'hover:underline font-medium text-blue-600' %></span>
            <% if user_signed_in? && current_user.email == post.user.email %>
              <div class="flex items-center gap-2">
                <%= link_to edit_post_path(post), class: 'text-blue-500 hover:text-blue-300 flex items-center' do %>
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
                  </svg>
                <% end %>
                <%= button_to post_path(post), method: :delete, class: 'text-red-500 hover:text-red-300 flex items-center' do %>
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                  </svg>
                <% end %>
              </div>
            <% end %>
          </div>
          <div class="flex items-center justify-between mb-2">
            <span class="block font-bold uppercase"><%= post.title %></span>
            <span class="block"><%= post.updated_at.strftime("%a %b %-d %Y") %></span>
          </div>
          <p><%= truncate(strip_tags(post.body.to_s), length: 200) %> <%= link_to 'See more', post_path(post), class: 'font-medium text-blue-600 hover:underline' %></p>
        </div>
      </div>
    <% end %>
  <% else %>
    <div>
      <p>No blogs found</p>
    </div>
  <% end %>
  
</div>